### ISSUE TITLE
Create release flow to eliminate need for snapshots

### ISSUE THREAD

**Issue by AW-STJ** [TokenScript/token-negotiator#105]
The task is from TokenScript but dependency on attestation.id

@foxgem - can you share your requirements.

**Comment by nicktaras** [comment]
Hi @AW-STJ / @foxgem

Is there any further details around this issue? What are snapshots with regards to this topic.

Thanks

**Comment by foxgem** [comment]
sorry, I missed this one. this should be in tokenscript/attestation which is dependency of attestation.id. basically, my requirement is a flow to define how and when we can release a package to npm (js code) or maven (java code).

in a summary, it is about how to make release plan and automate it. currently, no such things.

**Comment by nicktaras** [comment]
Sounds great @foxgem. I'll close this item and create this same ticket inside TokenScript attestation.
