### ISSUE TITLE
Fixme: to review / apply fix

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#107]
<img width="979" alt="Screen Shot 2021-11-11 at 12 53 14 pm" src="https://user-images.githubusercontent.com/6808817/141222945-a4342b2b-43b4-43f5-b830-6a9d69ad120a.png">

**Comment by oleggrib** [comment]
@nicktaras ,  Looks like its not my code. Do you need me to help fix that?

**Comment by nicktaras** [comment]
@oleggrib Thanks, sorry I had assumed you knew about this. I'll check the user of the commit and reach out to them to see if this is still a required action to take.
