### ISSUE TITLE
IOS Cross Site tracking Safari/Duck&Go/Firefox/Chrome - User must adjust their Settings to enable Negotiation of Tokens (Iframe communication))

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#112]
![IMG_4368](https://user-images.githubusercontent.com/6808817/142355967-446aad8b-4981-4f6b-8038-c1f52d030ad3.PNG)

From updates to security policies starting around 2017, the latest default setting for Mobile Safari Web is to block iframes from loading. 

Image attached: Showing which setting must be switched off 'Prevent Cross Site Tracking' to allow for negotiation of tokens.

**Comment by nicktaras** [comment]
https://discussions.apple.com/thread/250304102

**Comment by oleggrib** [comment]
@nicktaras , did you try and discover that issue for some of our examples?
Possibly it not affet us, because we dont save cookies from iframe, we just read cookies and communicate with postMessages.

**Comment by oleggrib** [comment]
@nicktaras just confirmed that negotiator_v1 affected to.
In that case we have to replace iframes with browser tab and browser can use same postMessages like we use for iframes right now. 
JS can open/close tabs and tabs are visible for user, so browser security policy should not block it in meantime. 
for example twitter opens seperate tab to login user.
cc @AW-STJ

**Comment by nicktaras** [comment]
Closing this issue with solution tickets in progress.
