### ISSUE TITLE
Active Negotiation | Design Architectural Change - Outlet and Overlay 

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#113]
Post Message is not permitted on many browsers including; Safari (MAC, IOS), Brave, Chrome (IOS).

As a work around to this problem, the use of Access API & Cookies can be used. 

See branch; https://github.com/TokenScript/token-negotiator-examples/tree/wip-access-storage

Technical Requirements:

**Fab Button**

1. Re-work how the Fab button is added to a client window. E.g. Scrape the HTML from Iframe and inject it into client html container.

**Tokens through Iframe**

1. Inject the Overlay module into the Outlet (library itself can be left un-touched to do this step)
2. Apply Access Storage API to allow Safari to read cookies (click button from within the Iframe, e.g. activate Negotiation)
3. When user clicks fab button, the Iframe is injected as before / or shown, hidden if this can be done.
4. Add Iframe button listener inside top window to read tokens, this via cookies.
5. Finding the tokens within the cookie, store them in the top windows local storage (attestations)
6. Utilise existing logic to update the client e.g. Hotel Bogota to re-learn the tokens on each user change. 
7. Ensure that the passive negotiation is not impacted by such design changes.

**Comment by nicktaras** [comment]
https://www.adoclib.com/blog/local-storage-cross-domain-safari-disables-it-by-default.html

**Comment by oleggrib** [comment]
Links to test postMessages
1. Add value to localStorage https://testshop.antopolbus.rv.ua/iframe/init.html
2. Open https://antopolbus.rv.ua/test/iframe_postMessage.html and click "Open Popup"

lines like 'received postMessage from child: {"iframeCommand":"ttt2","iframeData":"data from child"}' should appear every 5 sec

how it works:
- https://testshop.antopolbus.rv.ua/iframe/init.html adds record to the localStorage.
- https://antopolbus.rv.ua/test/iframe_postMessage.html opens https://testshop.antopolbus.rv.ua/iframe/ in the new tab
- https://testshop.antopolbus.rv.ua/iframe/  reads data from localstorage and postMessage it to the parent 
- https://antopolbus.rv.ua/test/iframe_postMessage.html display value.
- in 7 seconds parent tab will close child tab.

@nicktaras , can you test it in your devices to know if it works?

**Comment by nicktaras** [comment]
Closing this issue where the fix has now been implemented. 

Thanks for your demo to show how tokens can be stored via a tab Oleh.
