### ISSUE TITLE
Add a module to Negotiator for standard (image) NFT along side attestations when given contract addresses

### ISSUE THREAD

**Issue by AW-STJ** [TokenScript/token-negotiator#115]
@oleggrib - Tomek will produce a desired visual for such a scenario. Ideally, this work starts when @nicktaras finished his heroic struggle with cookies, as that struggle leads to huge change in code base -> conflicts with other work.

**Comment by oleggrib** [comment]
svelte app example to read NFT image/metadata
https://github.com/TokenScript/playground_nfts/blob/main/src/App.svelte

exmaple page: https://testshop.antopolbus.rv.ua/nfts/

@nicktaras , can you check if you can use code from that APP to read NFTs with Negoatiator?

**Comment by oleggrib** [comment]
this is how it looks for me
![image](https://user-images.githubusercontent.com/18176173/149022190-35c4f4d9-f41c-4a21-a70f-a990000996e8.png)
