### ISSUE TITLE
Redesign the attesation.id modal for the attestation verification OTP flow.

### ISSUE THREAD

**Issue by AW-STJ** [TokenScript/token-negotiator#119]
Acceptance Criteria:

This is an enhancement task to review the new design of the token negotiator and the attestation.id modal. This may not be required, but suggested for review where the designs have a slightly different look and feel.

**Comment by nicktaras** [comment]
Task created to address this: TKN-164

**Comment by hboon** [comment]
Passing by to suggest that we see if popup blockers presents a problem when opening a new tab.

**Comment by AW-STJ** [comment]
How does platforms like Twitter do opening up a new tab for authentication, from a third party website?

**Comment by oleggrib** [comment]
We have an issue to add option to force open TAB instead of iframe: https://github.com/TokenScript/token-negotiator/issues/248

negotioar includes switch to open TAB if iframe not supported, so it should be easy update. @nicktaras

**Comment by micwallace** [comment]
Popups aren't blocked when invoked from a user action, so it depends on how and when the popup is invoked. We can also detect the popup being blocked and present a button "authenticate" to trigger the popup via user gesture.

**Comment by nicktaras** [comment]
Closing this issue. This task is part of the development road map for the product and managed via Jira.
