### ISSUE TITLE
Design Question: Cross Origin Cookies / Security / Integrity / Architecture

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#121]
From hitting many walls with regards to managing tokens between iframes, such as using Post Message to send data cross origin, I have finally applied cross origin cookies as the solution.

This solution delivers the cookies (soft attestation data) to the desired website (via an iframe), however this data can also be obtained by a hacker (as one of many examples) if they installed the token negotiator on their website with the same config ("phishing", "farming" attacks etc). 

Oleh and I were just talking about this in more detail and wanted to check to ensure this approach is correct as per security requirements? Please can you add any comments / ask any questions / feedback. @colourful-land, @oleggrib, @jot2re (CC @AW-STJ).

Thanks guys

**Comment by jot2re** [comment]
@nicktaras just to clarify, you mean a malicious site can pose as, say hotel-bogota.com and request ab attestation via an iframe from attestation.id? And they can then inject this on the real hotel-bogota.com website? And similar with say, devcon ticket?
If I understand correctly, then this is an issue, since this undermines the trust-model we have put in place.
As far as I remember, last time we talked about this we discussed how the iframe would actually not directly share the attestation or ticket, but instead supply a ZK proof that they know the correct attestation or ticket. 
In particular this ZK proof will be made on an unpredictable number derived from the specific session and domain of the website. This prevent extraction of the attestation or ticket or reuse of the ZK proof by a malicious website.

**Comment by oleggrib** [comment]
@nicktaras , As I understand - current solution share cookies (magicLinks in the cookies) with any website? so everyone can access those magiclinks and read tickets+ticketSecrets? same for attestation.id - everyone can access attestation and read attestation+attestationSecret . correct?

in the previous iframe+postMessage flow secrets were hidden from users, even hotelBogota didnt have access to sercets, just to the proof.

**Comment by nicktaras** [comment]
> @nicktaras just to clarify, you mean a malicious site can pose as, say hotel-bogota.com and request ab attestation via an iframe from attestation.id? 

Because the lib is open source and based on a client side website, this is quite possible with all versions of the TN. To reduce the chances of being able to use a Devcon ticket on a non-supported site a white/black list could be used. 

As far as I remember, last time we talked about this we discussed how the iframe would actually not directly share the attestation or ticket, but instead supply a ZK proof that they know the correct attestation or ticket. In particular this ZK proof will be made on an unpredictable number derived from the specific session and domain of the website. This prevent extraction of the attestation or ticket or reuse of the ZK proof by a malicious website.

Can we further discuss this, I remember you saying this and also Weiwu mentioned using something like Hurricane Cash ZKP. 

To help continue the progress, I'll create a full flow of what the TN is currently doing with regards to handling the UN, signatures, Tokens and EthKey tomorrow.

**Comment by jot2re** [comment]
Sure, but I think it is better to discuss at a meeting than over text :) It becomes quite complex, quite fast. But basically what is needed is a challenge-response approach where hotel-bogota's backend server does a challenge-response with the iframe for attestation.id via TN. Basically it sends a message to the attestation.id iframe, which uses its cookie to compute a response, and return this back. 
This response will only work at this time, for this session with hotel-bogota and thus cannot be reused.

**Comment by nicktaras** [comment]
> @nicktaras , As I understand - current solution share cookies (magicLinks in the cookies) with any website? so everyone can access those magic links and read tickets+ticketSecrets? same for attestation.id - everyone can access attestation and read attestation+attestationSecret . correct?
> 
> in the previous iframe+postMessage flow secrets were hidden from users, even hotelBogota didn't have access to sercets, just to the proof.

This is correct in the previous version using cross origin post message was more secure. A hacker would find it difficult to gain access to the attestations. PostMessage by default is not cross-origin compatible with Brave and Safari Web & IOS.

**Comment by nicktaras** [comment]
> 



> Sure, but I think it is better to discuss at a meeting than over text :) It becomes quite complex, quite fast. But basically what is needed is a challenge-response approach where hotel-bogota's backend server does a challenge-response with the iframe for attestation.id via TN. Basically it sends a message to the attestation.id iframe, which uses its cookie to compute a response, and return this back. This response will only work at this time, for this session with hotel-bogota and thus cannot be reused.

Thanks @jot2re - it becomes a lot of text to read through : ) I'll book a meeting to look into this as the solution for tomorrow (if you have a preferred time to catch up just let me know).

**Comment by oleggrib** [comment]
> @nicktaras just to clarify, you mean a malicious site can pose as, say hotel-bogota.com and request ab attestation via an iframe from attestation.id?

if malicious site has magicLink or have access to the user email and can read OTP then it can generate attestation. but attestationSecret should stay under attestation.id domain and it can be requested by devconTickets website only. its secure flow.

**Comment by jot2re** [comment]
@oleggrib I am not sure I understand your point in this setting. If the malicious site has access to the user's email account (or the OTP) then yes, as you say, they can simply generate a "legitimate" attestation. But I thought the issue here was that Nick suggested that the attestation (or Ticket, or whatever other object) got shared directly with TN of the malicious site?

**Comment by jot2re** [comment]
I do recall, that we a had a very specific discussion for the [specific flow ](https://community.tokenscript.org/t/devcon-flow-that-shows-how-attestation-token-identifier-attestation-works-for-hotel-bogota-3rd-party-website/474)of combining both a Ticket and an Anonymous Attestation through iframes to both devcon and attestation.id. In that flow the we trust the devcon iframe to receive the secret from attestation.id and create a useTicket object to pass back to hotel-bogota.

**Comment by colourful-land** [comment]
I'm sorry but my head is pretty blank when I look at the security model of iframe based attestation. It has taken a seriously long time for @nicktaras to get something working, even though violating the security assumption (I didn't know cookie method was meant to pass data as-is between iframe and host, in my mind somehow I thought it was a message STORAGE mechanism for data). In fact, Nick spent so many weeks on this and we have neglected the important aspect of developer experience.

I propose we close nick's work as an insecure but working (in terms of usability) version, let's call it the 'dev branch', finish all the test cases and write a page about the testing method, then reassign it to @oleggrib for restoring security, so in the meanwhile, Nick can continue to work on developer experience which we badly need. Nick will need a meeting to pass knowledge to @oleggrib so let's make it the topic of the next TS meeting (which happens in 36 hours).

**Comment by oleggrib** [comment]
@nicktaras , @colourful-land 
I just created and tested in Brave browser solution to interact with child-tab (not iframe). It have same security level like iframe, but visible for users(It can be even helpful, so user can see actions and some company Logo's). Nick can test it in different browsers to see if it works good (I suppose that we have a chanse that some mobile browsers can freeze inactive tab scripts)
![image](https://user-images.githubusercontent.com/18176173/146843506-bd07d3b3-864b-47d1-87a1-0e47026d058a.png)

**Comment by nicktaras** [comment]
@oleggrib, @colourful-land, @jot2re - From testing this on Iphone this yesterday evening / this morning, it is as you mention above @oleggrib we have an issue. Apple and other websites are being extremely strict, not allow cross origin cookies without either:

A: Having the user explicitly enable cookies via the browser settings
B: Having the user visit the actual website page (window level), then return to the page e.g. hotel bogota.

**Comment by nicktaras** [comment]
The solution to navigate the user back and forth from a website, is a workable solution for Twitter auth. However if a user had to navigate across various token outlets each time you go to a token enabled site, would this work? It wouldn't be a great user experience, but would allow the cross origin post message to work etc. 

To flesh out this concept out, this would be the flow:

- The user would navigate to the outlets via magic links received via email.
- When visiting Hotel Bogota, Devcon (or any token enabled website), they would see the overlay inside the bottom of the page. With a list of all the supported tokens (these would be buttons to the Outlet urls per token type)
- These URLs would navigate the user to the outlet... then on load of the page it would re-direct back to the referrer

**Comment by nicktaras** [comment]
![Screen Shot 2021-12-21 at 11 11 17 am](https://user-images.githubusercontent.com/6808817/146849284-98119bb5-9c46-4ae1-8f39-b735912cbd1e.png)

Mock design to help illustrate the first step of the flow - The connect buttons for off chain attestations would open the outlets per token.

**Comment by jot2re** [comment]
> > Sure, but I think it is better to discuss at a meeting than over text :) It becomes quite complex, quite fast. But basically what is needed is a challenge-response approach where hotel-bogota's backend server does a challenge-response with the iframe for attestation.id via TN. Basically it sends a message to the attestation.id iframe, which uses its cookie to compute a response, and return this back. This response will only work at this time, for this session with hotel-bogota and thus cannot be reused.
> 
> Thanks @jot2re - it becomes a lot of text to read through : ) I'll book a meeting to look into this as the solution for tomorrow (if you have a preferred time to catch up just let me know).

Ah, sorry, I forgot to answer this. Generally any time between 9AM and 6PM CET works well for me :)

**Comment by nicktaras** [comment]
Closing this issue. 

The solution applied has two alternate flows implemented the TN (Iframe and Tab) to support browsers that don't support cross origin sharing of storage data via an embedded iframe.

Just to confirm, these solutions re-enable the level of security intended, where the token attestation data and secrets are kept inside the token issuer outlet/s (out of reach of the web developers who implement the Token Negotiator).
