### ISSUE TITLE
Security Review of Token Negotiator flows

### ISSUE THREAD

**Issue by AW-STJ** [TokenScript/token-negotiator#135]

**Comment by jot2re** [comment]
Review of the end-to-end flows according to the flows defined in https://miro.com/app/board/uXjVOTp0400=/

**Comment by jot2re** [comment]
The review is complete with the report submitted to @AW-STJ.
@AW-STJ should we close this issue and open any relevant issues that require fixing instead?

**Comment by nicktaras** [comment]
Closing this ticket.
