### ISSUE TITLE
TokenNegotiator and Shopify

### ISSUE THREAD

**Issue by zhangzhongnan928** [TokenScript/token-negotiator#144]
Suggested by Brent
We should connect token negotiator to the Shopify API and then list it as an app/plugin on their marketplace > we could then announce that 1m Shopify stores in 175 countries can now customise offers to NFT holders.

https://www.shopify.com/partners

**Comment by micwallace** [comment]
Completely agree, great idea. Eccomerce is a big use case for this. We will need to standardize a library for server-side validation of off and on chain tokens, which can then be used for multiple eccomerce platforms. 

I can certainly help with that and a Magento plugin if that's another platform we want to target :-)

On 23 March 2022 4:20:46 pm AEDT, Victor Zhang ***@***.***> wrote:
>Suggested by Brent
>We should connect token negotiator to the Shopify API and then list it as an app/plugin on their marketplace > we could then announce that 1m Shopify stores in 175 countries can now customise offers to NFT holders.
>
>https://www.shopify.com/partners
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/TokenScript/token-negotiator/issues/144
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by oleggrib** [comment]
another world-wide ecommerece is WordPress + Woocommerce

simpliest way and not user friendly , experienced dev required:
- plugin to embed negotiator to the page and API to interact with Negotiator
- some field to set token name
- backend plugin to validate objects or API to the trusted server to validate objects

more useful way:
1. plugin to inject negotiator to the shop frontend
2. backend with some configuration to add discount on token proof
3. validation module to make sure that attestation+token+proof is valid

its same for any ecommerce.

plugin can be free for base limited usage and paid for extended cases. (its usual for woocommerce)

**Comment by nicktaras** [comment]
Adding a link for preparation of this task:

https://shopify.dev/apps/getting-started/create

**Comment by nicktaras** [comment]
Closing this issue, we now have a Shopify solution. Great work on this @micwallace.
