### ISSUE TITLE
Outlet + Client on same page

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#174]
Usually user get MagicLink through email. So user click magicLink or copy-paste it and open it in the browser, so we have to keep in mind that step readMagicUrl() will not have document.referrer, so I disabled this check

And after readMagicUrl() finished user have to see some page, where he can see list of the tokens. Some nice looking landing page, which work like Client to get tokens to display.

In this case I suggest to change code back to solution, similar as I coded at beginning, where Outlet code embedded to the Client and fired when tokenOrigin==window.origin. In case if its parent window then page will act as Client+readMagicUrl()+landingPage, if its child then page will act as Outlet.

Makes sense? @nicktaras , @micwallace

**Comment by nicktaras** [comment]
Closing this ticket. Where the Outlet and Client Modules can be included inside a single page as seen inside the initial demo of TN.
