### ISSUE TITLE
Review package.json dependencies

### ISSUE THREAD

**Issue by samwarwick** [TokenScript/token-negotiator#179]
package.json appears to contain quite a few redundant packages. Any used packages should be removed.
Does `npm` really need to be included as a devDependency?

Output from running https://github.com/depcheck/depcheck (`npx depcheck`) against main branch on 26-apr-2022:

```
Unused dependencies
* big-integer
Unused devDependencies
* @types/create-hash
* @types/jsdom
* @types/keccak
* @types/prop-types
* @types/react
* @types/readable-stream
* assert
* axios
* babel-core
* babel-loader
* babel-plugin-transform-runtime
* babel-polyfill
* babel-preset-es2015
* babel-preset-stage-0
* browserify
* buffer
* crypto
* envify
* install
* process
* terser-webpack-plugin
* typescript-plugin-css-modules
* url
* webpack-cli
Missing dependencies
* tslint: ./tslint.json
* webpack: ./webpack.config.js
```

**Comment by nicktaras** [comment]
Thanks for raising this issue @samwarwick really appreciate it.

We'll remove all unused dependencies from the next up and coming release.

**Comment by nicktaras** [comment]
Closing this issue. Deps have been reduced in main branch and due to be released.

Thanks @samwarwick
