### ISSUE TITLE
Brand Connector Fashion demo not working

### ISSUE THREAD

**Issue by AW-STJ** [TokenScript/token-negotiator#217]
The music demo works fine. Its is just the fashion page that is not responsive to activating the tokens.

![image](https://user-images.githubusercontent.com/61957841/169431068-f4fb914b-011d-470f-9265-31b10bcada2e.png)

**Comment by micwallace** [comment]
@AW-STJ this page requires Nifty derivative or womens tribe tokens. I just tested and it's working as expected.

**Comment by AW-STJ** [comment]
Okay. That makes sense. Thanks Miccy for the clarification.

**Comment by micwallace** [comment]
@AW-STJ nick found some small text which was referring to the wrong token, which is probably how you were mislead. He's updated to correct and pending deploy by Feng.
