### ISSUE TITLE
To confirm the request / response (input output flow)

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#24]
The progress has been started to confirm the network flow to complete the authentication / attestation process.

This ticket is to share the mock flow, then confirm the details are correct to use a devcon ticket.

**Comment by nicktaras** [comment]
<img width="718" alt="Screenshot 2021-06-24 at 23 13 33" src="https://user-images.githubusercontent.com/6808817/123269185-1746b600-d542-11eb-9724-278713280393.png">

This is a work in progress flow of what happens when the end user selects to use their ticket.

**Comment by nicktaras** [comment]
<img width="668" alt="Screenshot 2021-06-24 at 23 16 30" src="https://user-images.githubusercontent.com/6808817/123269340-3b09fc00-d542-11eb-9f4b-372991bdc7cd.png">

This is a mock flow of when an end user selects to use their ticket

**Comment by nicktaras** [comment]
@colourful-land and @oleggrib could you take a look at the screen shot providing any feedback.

**Comment by oleggrib** [comment]
https://github.com/TokenScript/attestation/blob/javascript-crypto/src/main/javascript/negotiator/demo.html#L92-L110
can you check that flow?
let n = new Negotiator(filter,
        // "https://devcontickets.herokuapp.com/outlet/" hardcoded as default value, we can change it if needed
            {
                tokensOrigin,
                attestationOrigin
            }
        );
n.negotiate(callback) - to receive tokens
n.signToken(tokens, callback) - to sign token and receive useTicket object

**Comment by nicktaras** [comment]
Hey @AW-STJ just tagging you here for visibility as we work to complete this last part of the flow.

**Comment by nicktaras** [comment]
![Screenshot 2021-06-25 at 10 35 10](https://user-images.githubusercontent.com/6808817/123351705-0e390180-d5a1-11eb-8ea9-909e40452307.png)

**Comment by nicktaras** [comment]
Updated the flow to sign ticket with negotiator.

**Comment by nicktaras** [comment]
![authenticationFlow-diagram](https://user-images.githubusercontent.com/6808817/123575457-23b66180-d815-11eb-98c6-fd6a5fd2312e.png)

**Comment by nicktaras** [comment]
![authenticationFlow-Page-updated](https://user-images.githubusercontent.com/6808817/123578915-2798b280-d81a-11eb-9c91-bb7a8aa66c8c.png)

**Comment by nicktaras** [comment]
![authenticationFlow-Page-1](https://user-images.githubusercontent.com/6808817/123579229-dc32d400-d81a-11eb-880a-e88a1579e734.png)

**Comment by nicktaras** [comment]
Closing this ticket. This flow has been confirmed and implemented.

**Comment by nicktaras** [comment]
![authenticationFlow-Team-Design](https://user-images.githubusercontent.com/6808817/124111722-eff56900-daac-11eb-8bf7-e8292bb3e7e8.png)

Final flow.
