### ISSUE TITLE
Confirm Negotiator storage object

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#25]
In the current design for the token-negotiator, the token-outlet webpage stores the token data in two parts:

- token
- secret

Should a hacker make their way to the origin token-outlet page (on someone else's computer), they will be able to find, then use the token to view offers / discounts and see other features a non-ticket holder would not have.

(Note: just to clarify this would not mean they can spend the ticket - which would require attestation).

This ticket is to confirm: What is the correct approach / more secure approach we wish to take? 

![Screenshot 2021-06-23 at 16 50 51](https://user-images.githubusercontent.com/6808817/123098982-13992d80-d475-11eb-8e1c-f683fbb7ae4c.png)

**Comment by nicktaras** [comment]
Mention from today's meeting, https://tornado.cash/ - as a technology which mixes transaction data (overtime) in return for privacy.

**Comment by oleggrib** [comment]
data saved in user browser. cross-domain localStorage read is not allowed, so hacker can interact with our script only and receive tokens list only (without secrets)
if hacker has access to the user browser then we can't change that, but if not, then hacker can't access tiket secret + attestation secret

**Comment by nicktaras** [comment]
closing this ticket. This flow has now been resolved.
