### ISSUE TITLE
Vulnerable and Outdated Components

### ISSUE THREAD

**Issue by jot2re** [TokenScript/token-negotiator#253]
There are dependencies used in the front-end with security issues rated critical.

See section 2.6 in the NFT Minting security report.
[See Jira issue 291.](https://smarttokenlabs.atlassian.net/browse/PR-291)

**Comment by nicktaras** [comment]
@oleggrib just let me know if I can help with any of the tasks inside this ticket (from looking in Jira the tasks are currently assigned to you).

**Comment by jot2re** [comment]
@nicktaras it is just a matter of running `npm audit fix` and pushing package fixes into production (assuming all tests work afterwards).
Also do an extra `npm audit` afterwards. Because there might be a risk that things don't get auto upgraded if the safe version of the dependency contains api changes.

**Comment by jot2re** [comment]
The task is mostly about making sure that nothing breaks after upgrading and potentially make some minor api changes if this is needed to upgrade :)

**Comment by nicktaras** [comment]
@jot2re

<img width="660" alt="Screen Shot 2022-06-30 at 12 42 35 pm" src="https://user-images.githubusercontent.com/6808817/176581432-d65efb6f-0426-4753-a849-d571e9912785.png">

Can I confirm, are these all the updates needed your side as part of the security review. 

I'll update these from the screen shot manually rather than force a fix (if possible).

**Comment by nicktaras** [comment]
From making this suggested change it causes another issue:

1 low severity vulnerability

Insecure Credential Storage in web3 - https://github.com/advisories/GHSA-27v7-qhfv-rqq8

fix available via `npm audit fix --force` will install web3@1.7.4, which is a breaking change.

<img width="621" alt="Screen Shot 2022-06-30 at 2 48 50 pm" src="https://user-images.githubusercontent.com/6808817/176595114-1fd22b27-638c-49d6-8f48-9a9222112815.png">

**Comment by nicktaras** [comment]
@micwallace picked this task up for me https://github.com/TokenScript/token-negotiator/pull/275

@jot2re - I'll let you know when we next release for you to be able to see the dependancy issues removed. Thanks.

**Comment by nicktaras** [comment]
Closing this issue, the solution is now in staging and due to be released soon.

(Will reopen if needed)
