### ISSUE TITLE
[Fix] Add option to disable authenticate() for some browsers as temporary fix

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#257]
Currently we have few wallets, which doesnt work correctly :  
- Metamask internal browser can't work correctly with attestation.id
- Android Alphawallet cant sign data when private key was imported

so we need some way to notify user that current browser not supported and throw error if user use it. We need this check at step clientInstance.authenticate() 

example code by @snowwhitedev to find out that its wallet-internal-browser is: 
https://github.com/AlphaWallet/attestation.id/pull/152/files

so in case if we find out that some browser have problem then we can add it to the list and stop user use it until we fix issue.

@AW-STJ @micwallace @BastianAlpha

**Comment by nicktaras** [comment]
Thanks @oleggrib, I'll look into this in the current sprint.

**Comment by oleggrib** [comment]
@snowwhitedev , did you test your code snippet?  https://github.com/AlphaWallet/attestation.id/pull/152/files
Does it separate Android Chrome from Metamask internal wallet?

**Comment by snowwhitedev** [comment]
> @snowwhitedev , did you test your code snippet? https://github.com/AlphaWallet/attestation.id/pull/152/files Does it separate Android Chrome from Metamask internal wallet?

Yeah. I tested it in Android Metamask internal browser

**Comment by oleggrib** [comment]
> Yeah. I tested it in Android Metamask internal browser

yes, but it matches Android Chrome too, so we cant use this way to detect Wallet Internal browser @snowwhitedev

**Comment by oleggrib** [comment]
@nicktaras , I updated your script to detect MEW, Alphawallet, Metamask, ImToken
https://testshop.antopolbus.rv.ua/agent/agent.html
you can use it in TokenNegotiator.

just have to note that window.ethereum.isMetaMask == true for multiple wallet browsers, so it can help us prevent to use untested wallet browsers

@micwallace @AW-STJ

**Comment by nicktaras** [comment]
Closing this ticket, we not have fixes and this fall back logic in place to inform users when their browser is not supported.
