### ISSUE TITLE
[Idea] Make the brand connector button a moveable floating button

### ISSUE THREAD

**Issue by colourfreak** [TokenScript/token-negotiator#258]
https://user-images.githubusercontent.com/51817359/175113693-2e8afb35-5663-49b9-b4a0-8367f9e579da.mov

**Questions from Basti:**
> 1) How would this work on mobile ? would this be desktop only ?
> 2) Have you seen other product (plugins) on ecommerce and similar stores that use this concept ?
> 3) do you think people would be confused if they accidentally hide the icon ?
> 4) what do you think is the users reaction (aka are they getting confused) if the icon floats and is always on different positions when visiting the same or different websites ?

**My answers:**
1. The same way the customer support chatboxes work. https://www.nngroup.com/articles/chat-ux/ 
2. Yes. Chatboxes.
3. Same if they would hide chatbox. In other words, they don't rely only on floating buttons.
4. It should start in the same place always - bottom right. 

What I envision in the future, is the wallet/brand connector to run with a similar experience to a password manager. Take 1Password for example. On the desktop, you have an extension + desktop app that runs in the background and it's triggered when needed. Usually when it sees an input field.

On mobile devices, you can set up this Autofill Password with... (you select an app), and from that moment on, it will be triggered automatically. 

But for that to happen, Apple and Android team has to create that function in the Settings. We are still not there. 

Anyway, what I think we could do is create a small icon (like a safe payment badge on an e-commerce website when checking out or a Tripadvisor sticker on the entrance to every restaurant). Something that can be recognized as - you can negotiate a price with a brand connector. Then you can trigger a floating button. Otherwise, it might be annoying to have it all the time on screen and you are competing for real estate on-screen against the chatbox - which might be more desired for e-commerce businesses.

**Comment by colourfreak** [comment]
Ideally, that small badge (kind of like safe checkout ones) on a screen could immediately show you the saving amount - so you are even more incentivized to open a brand connector.

**small badge examples:**
![images](https://user-images.githubusercontent.com/51817359/175121107-cb1c3b32-a13d-4799-90d3-1298940e8857.jpeg)

**Comment by nicktaras** [comment]
Thanks for this innovative idea @colourfreak 🚀 We've moved this idea into our roadmap planning to review and consider for implementation.
