### ISSUE TITLE
Shared Array Buffer Isolation - Solution required to ensure token-negotiator is not impacted

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#26]
![Screenshot 2021-06-24 at 12 23 51](https://user-images.githubusercontent.com/6808817/123195217-251d1c80-d4eb-11eb-8f50-761fdebc2a93.png)

Google are to also soon deprecate cross site sharing of cookies through Iframe -  around July 2021.

A solution must be found to ensure the Token-Negotiator is functional across all popular browsers / devices.

**Comment by oleggrib** [comment]
looks like cross-domain interaction works good with ,my last demo.

**Comment by nicktaras** [comment]
Yep, we can close this. This seems to be a warning from react apps, using web workers and not directly related to the work we are doing from taking a close look at this. 

https://blog.logrocket.com/understanding-sharedarraybuffer-and-cross-origin-isolation/
