### ISSUE TITLE
Security issue because of web3

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#262]
Currently token-negotiator use "web3" npm module to work with Torus provider, but web3 has security issue because of dependent module "got".

Easiest fix is to remove web3 and user ethers.js instead.

@micwallace , @nicktaras , do we have some specific reason to use web3 instead of ethers.js ?

remove web3 can save some space and make negotiator bit smaller.

**Comment by nicktaras** [comment]
Closing this issue, fix has been added into Staging.

(Will re open this issue if needed)
