### ISSUE TITLE
AW browser UX with Token Negotiator

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#286]
Two UX issues found when navigating the Token Negotiator Examples via AW.

Link to examples: https://tokenscript.github.io/token-negotiator-examples/

To replicate the following issues. 

1. Use AW browser for the following steps
2. Navigate from the AW browser to: https://tokenscript.github.io/token-negotiator-examples/
3. Click on the "Ticket Issuer" Link, creating a ticket attestation (triggering issue # 1 below)
4. Click back to get to the Menu and select the demo Hotel Bogota Active
5. Use the token negotiator to connect your wallet
6. Once connected, navigate to book a hotel room and select to 'apply discount'
7. Then complete the following steps inside Attestation.id (triggering issue # 2 below)

#1 When navigating to create a ticket attestation the browser navigates and gets stuck on a blank web page. Token Negotiator creates a tab window to store the attestation, then close the tab > navigating back to the original. However shared in this issue, the Tab doesn't close. As a work around the user must navigate back. 

<img src="https://user-images.githubusercontent.com/6808817/177089106-cbea8438-ec56-44da-abab-0b7ebf794fbd.PNG" width="150px"> 

#2 Full attestation flow, when authenticating tickets via attestation.id at the point of submitting the OTP code the screen shows the following screen - see: https://github.com/TokenScript/token-negotiator/issues/257

<img src="https://user-images.githubusercontent.com/6808817/177089174-8bb63786-6e29-47bb-8a15-3e04e419a4f4.PNG" width="150px"> )

**Comment by oleggrib** [comment]
https://github.com/AlphaWallet/attestation.id/issues/141 - its same issue, @nicktaras , this why we need https://github.com/TokenScript/token-negotiator/issues/257

**Comment by nicktaras** [comment]
@oleggrib I've updated the details on #2 to point to #257. Item 1# is a newly defined issue.
