### ISSUE TITLE
Avoid unneeded connect to wallet in popup for off-chain tokens

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#290]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/18176173/177896887-a2bd81c3-a237-4192-8961-dc768c9c6006.png">

In this case user need to unlock and connect wallet even if user will not decide to sign something. Sometimes waletcConnect can break connection on some timeout, so this connection can be sense-less.

Also user can connect wallet connect and lock phone, so phone will not request user to sign until user understand that he need to unlock phone

Better avoid connect wallet at this stage and connect wallet immediately before sign message
@nicktaras @micwallace

**Comment by nicktaras** [comment]
Thanks @oleggrib. If I understand, you meant that for Off Chain Flows there is no requirement needed for a connection / signature to be made in this example which is correct. Let's confirm in our next meeting/s and we can add a task to update this.

**Comment by oleggrib** [comment]
@nicktaras , yes, I mean for off-chain tokens no need to connect wallet until really required to sign message. in some cases signing process can fail if wallet  connected some time ago.

**Comment by nicktaras** [comment]
Added to TKN Jira

**Comment by micwallace** [comment]
@oleggrib merged into staging
