### ISSUE TITLE
Example page doent ask to select token and doesnt follow deny sign message

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#291]
https://tokenscript.github.io/token-negotiator-gh-pages/hotel-bogota-active-negotiation-website/index.html

When user deny sign TX it still allow to "Pay". Screenshot after deny to sign:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/18176173/177898583-8b9cb2da-fa2c-491e-aa32-b5ad52840c1d.png">

Popup doesnt ask to select which token to use:
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/18176173/177898672-4427185f-fd4f-4883-b88b-2d0e6f5901b3.png">

@nicktaras

**Comment by nicktaras** [comment]
Thanks Oleh, this is noted as a change. I'll leave this issue here as a reminder pick this up in the coming sprints.

**Comment by nicktaras** [comment]
Added this item to Jira TKN.

**Comment by nicktaras** [comment]
Closing this ticket @oleggrib - I've updated the flow so the user can pay with no discount, or pay with the discount.
