### ISSUE TITLE
Negotiator doesn't work in Safari

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#323]
When negotiator runs in Safari then it tests and understand that Safari doesnt allow to read data from iframe.
As result - negotiator try to open iframe, but Safari blocks iframe until user click to approve it.
Negotiator receives error message from browser "Popup closed or blocked". In this case we need to open popup after some user action.
It can be handled by negotiator or send some error message to the webster to request it again on some action

@nicktaras , @AW-STJ

**Comment by micwallace** [comment]
@oleggrib better popup handling has been added to staging (future v2 release). For an example of how to use this in passive mode, see https://github.com/TokenScript/token-negotiator-examples/blob/2815e8375e6844cde93ae389a994ac5c951d322f/hotel-bogota-passive-negotiation-website/src/App.js#L74
