### ISSUE TITLE
Use single error channel for Client

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#326]
currently multiple types of error messages we can see in the authenticate() and negotiate() flow.
it can be:
- response.error:string[] from "token-proof" listener for "The redeem proof did not verify", "Ticket Signature is invalid" ...
- response.error:string from "token-proof" listener for "USER_ABORT: The user aborted the process" 
- response.name:string from "error" listener for "POPUP_BLOCKED"
would be good to use common error format, we can even use your "NamedError" with _name_ and _message_ (or with error code , like in HTTP) and would be good to return error to the listener, where we are waiting for responce, not to separate listener.

So when we request proof then we will get proof or error, some for negotiate()

what do you think @micwallace , @nicktaras ?

**Comment by micwallace** [comment]
I agree we should try to standardise the errors. The problem with negotiate (in active mode) is that multiple "token-selected" events can be emitted, hense why I decided it would be better to have a separate error event. 

For authenticate, the function can be called with await and surrounded by a try-catch. And a single request will get a single result. This can also be done for negotiate in passive mode, however there may be multiple errors, each related to a different issuer. 

Maybe we keep the error event to emit errors as they happen, but we also collect each error, and return them  keyed by issuer once negotiation is complete.

**Comment by micwallace** [comment]
@oleggrib For now I have updated token-proof error so it is always an error object, rather than string[].

**Comment by nicktaras** [comment]
Created a ticket for this.
