### ISSUE TITLE
Token negotiator React quick start issue.

### ISSUE THREAD

**Issue by snowwhitedev** [TokenScript/token-negotiator#355]
I had a chance to see and run React + Token Negotiator quick starter, but I got this error
![screenshot](https://user-images.githubusercontent.com/58669769/184676349-7b222977-a30d-4a4c-9bbf-09a8a28def19.png)

**Comment by nicktaras** [comment]
Thanks @snowwhitedev for sharing this issue. Can you share which react example you were using and any steps you took when this error was shown?

**Comment by snowwhitedev** [comment]
> Thanks @snowwhitedev for sharing this issue. Can you share which react example you were using and any steps you took when this error was shown?

I tried create-react-app (npx create-react-app my-app)

**Comment by nicktaras** [comment]
@snowwhitedev - This is a known issue across web3 technology that uses features such as; BigInt, Crypto, Stream.

The work around is to use React-ReWired which enables for Webpack 5 polyfills. 

See this example here, or alternatively the UMD module can be used. 
https://github.com/TokenScript/token-negotiator-examples/tree/main/art-gallery-medium-article-website
