### ISSUE TITLE
Examples doesnt work in safari

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#372]
It try to connect to Metabask , but safari doesnt have Metamask extansion.

Error: Unhandled Promise Rejection: Error: MetaMask is not available. Please check the extension is supported and active.

So user cant book ticket.

Solution: dont use Metamask as default provider and use _web3modal_

**Comment by nicktaras** [comment]
@oleggrib could I ask if this is still an issue from the recent updates made?

If so, can you share the steps you took to see this error to replicate and fix.

**Comment by oleggrib** [comment]
@nicktaras great, Metamask problem fixed, but flow still doesnt work in Safari/Mac
https://tokenscript.github.io/token-negotiator-gh-pages/hotel-bogota-active-negotiation-website/index.html
attestation.id Auth0 iframe problem :-(
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/18176173/189782122-835505d7-d019-4c30-91e7-d17d9f6f85fb.png">

**Comment by tcglam** [comment]
Not an issue anymore
