### ISSUE TITLE
Add option to return signedTicket object in "negotiate"

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#381]
In cases when we dont work with money we can do simplified attestation - validate ticket signature only

it will improve UX and require single click only

but we can't share signed ticket to any requestor, because it can be copied and used on other pages. (scammer can use hidden iframe to reads all user tickets data if we dont use whitelist)

what we have to update to make ticketAttestation flow secure as possible:

1. move tokenConfig to separate file so all TN instances will read it from single location. its important to avoid confision of different configs for same token. I implemented it simply: https://devconnect.smarttokenlabs.com/devconTokenConfig.js . Later we can read config from XML file. 
2. Add to the config "whitelist" field, where we can add list of domains
3. negotiator have to return to Whitelisted domains decoded tickets + signed Ticket. Other domains will receive only decoded tickets (like it works right now)
4. Remove signedTicket from input data for authenticate() 

@micwallace @AW-STJ @nicktaras , does it make sense?

**Comment by micwallace** [comment]
@oleggrib looks pretty straight forward to me. I'll get this done over the next few days.

**Comment by nicktaras** [comment]
Added to the project board, next sprint.
