### ISSUE TITLE
Improve from when Client() use same origin as Outlet()

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#404]
We often use cases when same domain show tickets and store them in localStorage.
In this case we can optimize flow to avoid iframe and start Outlet() instance in Client()

UX will be significantly improved for Safari, because right now user have to click button to show tokens and new tab blinks on screen, but we can easy simplify this without any issues.

@nicktaras , @micwallace , could you , guys, help with it? its relatively quick update.

Outlet() and Client() can compare new URL(issuer.tokenOrigin).origin and document.location.origin , if it the same then use simplified flow without iframe or new tab.

make sense? 
cc @AW-STJ

**Comment by micwallace** [comment]
Yep no worries Oleg, this was something I was thinking about doing.

**Comment by AW-STJ** [comment]
> if it the same then use simplified flow without iframe or new tab.

This is perfect if we can do this. UX is the biggest element that people would be judging our tech on. What exactly goes in background is not as interesting to vast majority of the users.

**Comment by micwallace** [comment]
@oleggrib This is implemented for token loading in #405

**Comment by tcglam** [comment]
https://smarttokenlabs.atlassian.net/browse/TKN-399 ticket created to track this issue
