### ISSUE TITLE
Simplify user whitelist flow

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#415]
In current flow BC asks user to Allow/Deny share tokens and save result in localStorage
I suggest to check parent / callback domain and if it already in tokenConfig whitelist then dont ask for permission and allow access.
In this case most of our customers doesnt need to click one more button (all Chrome / Safari / Brave users) and security will stay the same, because we will whitelist pages, developed by us or reliable sites.

I suggested this flow before, but we didnt have free time to implement it, but its is easy enough update.

make sense?
micwallace nicktaras @AW-STJ

┆Issue is synchronized with this [Jira Task](https://smarttokenlabs.atlassian.net/browse/TKN-420) by [Unito](https://www.unito.io)

**Comment by micwallace** [comment]
This is implemented on staging and deployed to outlets. Any domain on perks page can now be added to the whitelist.

**Comment by AW-STJ** [comment]
Awesome! Great job @micwallace
