### ISSUE TITLE
Detect/improve Browser support for all browsers

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#422]
I tried TN with mobile browsers and it mostly doesnt work. works only with metamask android

we have 3 ways to get ticket list

1. iframe
1. new tab
1. redirect

new tab helpful for Brave and safari, so I think we can skip NEW TAB flow at all

iframe+REDIRECT will be enough to support all browsers, even for wallet browsers and mobile client browsers

micwallace nicktaras

┆Issue is synchronized with this [Jira Task](https://smarttokenlabs.atlassian.net/browse/TKN-430) by [Unito](https://www.unito.io)

**Comment by nicktaras** [comment]
Closing this ticket, where these issues have been addressed.
