### ISSUE TITLE
getUseTicket method is missing in authentication flow

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#63]
![Screenshot 2021-10-05 at 12 43 32](https://user-images.githubusercontent.com/6808817/136117292-37f23694-9ab2-4405-a573-3b0de44f617e.png)

**Comment by oleggrib** [comment]
getUseTicket inside authenticate(), so in screenshot you can see result of that method.
![image](https://user-images.githubusercontent.com/18176173/136150890-62fb5483-b901-486b-b7a7-3df700529a32.png)
