### ISSUE TITLE
Set up Automatic Semantic Versioning + Publish Step inside CI Config

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#65]
This task should include:

- npx semantic-release-cli setup
- following steps to configure the package
- add documentation for other developers to install the package, access tokens, etc.
- add a publish step to the actions CI, this should build > test > publish to NPM

See: https://www.youtube.com/watch?v=QZdY4XYbqLI

**Comment by samwarwick** [comment]
For further reference: https://docs.npmjs.com/about-semantic-versioning

**Comment by nicktaras** [comment]
Closing this ticket. 

- plans for automatic semantic release will be paused for now
- NPM package discloses information how to get started/also see examples https://github.com/TokenScript/token-negotiator-examples
