### ISSUE TITLE
Community integration - Truffle 

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#66]
"truffle unbox tokenscript"

Create a truffle box for TokenScript.

This box could include / but not required for this first configuration:

- Demo Dapp
- Contract to deploy an ERC-721 token
- CLI generate TokenScript file
- Utilise Token via token negotiator within Dapp
- Full Attestation of ownership flow

**Comment by oleggrib** [comment]
@nicktaras , for example, I use hardhat rather then truffle, I have more experience with hardhat, but truffle is similar
> Demo Dapp 

it should install sample browser Dapp, corect? what that test app should do? what simple tasks? 

> Contract to deploy an ERC-721 token

maybe you mean "install package with example ERC721 contract + script to deploy"?

> CLI generate TokenScript file

do you mean to generate TokenScript file for ERC721 token for contract from previous step?

**Comment by nicktaras** [comment]
This task has not been required / requested to develop. Removing.
