### ISSUE TITLE
Confirm location of the Authenticator package

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#7]
The directory crypto was taken from the latest work from attestation. This should be the most up to date version of the negotiator and authenticator modules.

- The src/ needs to be updated to use the code inside the /crypto directory
- The crypto dir doesn't appear to build at the moment (fix)
- When merged if possible, the demo examples should still be able to run (some errors are expected until full integration is done)

**Comment by nicktaras** [comment]
The Negotiator is now merged.

To confirm the remaining tasks with the Oleg for the Authenticator, which may be possibly developed inside a different package / module (to confirm).

**Comment by nicktaras** [comment]
From previous meetings there is an understanding that the Authenticator may be a different module from token-negotiator?

This ticket is to confirm the location of this package. So work can be done to finalise integration.

**Comment by nicktaras** [comment]
(Note: Negotiator is written with JS and Authenticator is written with Typescript - where to merge into one package one type of scripting language would be best practice / make most sense).

**Comment by oleggrib** [comment]
Most of pages doesn't need Authenticator so for most of the we can use light Negoatiator. (hotel bogota, magicLink destination page)
But TokensHolderPage (in out case its DevconTickets) require Negoatiator+Authenticator.

**Comment by nicktaras** [comment]
Just to check - do any of these steps need the authenticator below:

with the negotiator, TPS opens iframe to DT and requests DT for tickets list with EP/CA
DT iframe answers with list
negotiator returns promise with the list of tokens the user allowed to use on TPS
later, TPS requires the token to be authenticated (i.e. user is in booking confirmation). when that happens:
DT request AttestaionId for attestation+secret
DT creates useTicket object and signs it
DT sends signedUseTicket to TPS
TPS sends signedUseTicket to the TPSBackendServer
TPSBackendServer sends signedUseTicket to some AUTH_SERVER API for validation
if AUTH_SERVER API answer valid then TPSBackendServer creates user session or add current user prmission to have Ticket benefits and send updated products list to the TPS

**Comment by oleggrib** [comment]
DT(negotiator) request Authenticator to create useToken (useTicket) 
Authenticator requests AttestaionId for attestation+secret
Authenticator creates useTicket object 
Authenticator returns useTicket to DT(negotiator) 
DT(negotiator) send useTicket to TPS

**Comment by nicktaras** [comment]
@oleggrib can we close this item. Or should we review this further?
