### ISSUE TITLE
Confirm Attestion.id requirements / User experience with Team

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#70]
Confirm the user experience for the attestation.id modal when used with the token negotiator.

- Controls, e.g. when the ticket issuer does not want to use email attestation (can the modal be hidden via a config)
- UX when the attestation.id modal should show / comms with token Negotiator and authenticator

**Comment by nicktaras** [comment]
Thanks @foxgem. 

The Token Negotiator uses this via the Authenticator - I will take a look at this during this current week and learn this part of the flow. 

We need to add some smarts to this flow - So the attestation.id doesn't popup into the view if the website isn't asking for OTP flow. This could come from the TokenScript file setting e.g. if Devcon do not want this feature.

**Comment by oleggrib** [comment]
@nicktaras 
In the flow Token Negotiator + Authenticator control display or not iframe. 
its data.force property of postMessage.

we display iframe when user have to confirm use of them Wallet.

**Comment by nicktaras** [comment]
Closing this ticket. This is being managed and worked upon.
