### ISSUE TITLE
Warnings when install the package

### ISSUE THREAD

**Issue by futantan** [TokenScript/token-negotiator#729]
Steps to reproduce:
- init a project
- add as deps
like this:
```json
{
  "name": "aaaa",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@tokenscript/token-negotiator": "2.7.1"
  },
  "author": "",
  "license": "ISC"
}
```

Got lots of warning in the console, maybe we can improv
<img width="1474" alt="CleanShot 2023-06-19 at 17 31 24@2x" src="https://github.com/TokenScript/token-negotiator/assets/6268441/45f5cf10-d847-4672-adce-ee819c46ac0e">
e this by upgrading the deps.

**Comment by futantan** [comment]
cc @nicktaras @micwallace

**Comment by nicktaras** [comment]
Thanks @futantan. 

We're currently removing WCv1 this should remove many of these warnings. With any that remain I'll create a Jira ticket for us to remove them in the next release after this up and coming major version release.

**Comment by nicktaras** [comment]
@futantan 

From version 3.0.0 many of these warnings will be removed. 
The WC warning is still present where we are using a lib that works for both 1 and 2 as a solution to support TKN.

I'll close this issue and address the WCv1/2 in a following release.
