### ISSUE TITLE
Selenium End to End Tests

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#76]
As a means to help mitigate bugs within the Token Negotiator NPM package and examples, end to end tests are required.

Acceptance Criteria:

- End to End tests to be developed with Selenium (with any additional tooling e.g. cucumber, source labs)
- Tests made to run across major browsers, both desktop and mobile devices
- Tests produce a report
- Document issues inside Git repositories (assignee, bug summary, steps to reproduce)

Links:

https://github.com/TokenScript/token-negotiator-examples - See link to examples inside README.md

**Comment by samwarwick** [comment]
IMHO alternatives to Selenium are worth considering. e.g. [Cypress](https://www.cypress.io/) and [Playwright](https://github.com/microsoft/playwright).
Interactions with MetaMask will be challenging. https://github.com/Synthetixio/synpress could provide a potential solution.

**Comment by samwarwick** [comment]
Another MetaMask option: https://github.com/CraftAcademyLabs/cypress-metamask

**Comment by samwarwick** [comment]
> Another MetaMask option: https://github.com/CraftAcademyLabs/cypress-metamask

According to https://github.com/CraftAcademyLabs/cypress-metamask/issues/9 this project is dormant. It has been forked to https://github.com/saxenashivang/cypress-metamask-v2

**Comment by nicktaras** [comment]
Closing this issue. This requirement is being solved inside another repo which will ensure the examples repo and any locations using the TN can be tested easily.
