### ISSUE TITLE
Github Pages Demo - Update Plan from recent changes

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#79]
This task is to update the Github Pages Demo with the latest changes to the Token Negotiator / Include plan via discord thread.

The outcome of this task should be:

- Code updates
- a fully functional git hub pages demo, showing how tickets can be generated and used in light and full authentication
- deliver before Wednesday this week 20th Oct

To confirm:

@oleggrib - what changes are required, attestation.id security fix / updates / devconTicket / TokenScript config / progress update and steps to apply next
@nicktaras - to help implement the changes

Fall Back / Plan B:

Use the original version where tickets are generated inside the ticket-issuer webpage

**Comment by oleggrib** [comment]
To fix MagicLink attestation security issue we need to update:
1. https://github.com/TokenScript/attestation/pull/194 - waiting for @JamesSmartCell to fix SmartContract test
2. Update Attestation.id with new attestation package
3. Update TokenNegotiator to use TokenScript XML config
4. Remove SignedDevonTicket.js from TokenNegotiator and add TicketSchemaDescription to the TokenScript XML config
@colourful-land , does that make sense?

Fallback flow - 
3. + 4. - use previous version of Negotiator until new version ready. I already have updated version of the previous Negotiator, so this step is done

**Comment by nicktaras** [comment]
Thanks @oleggrib
