### ISSUE TITLE
Documentation and example for negotiator.authenticate()

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#80]
Include documentation and example for negotiator.authenticate().

This task is to provide a code example of what a developer would do to acquire the unEndPoint.

const { useToken, useEthKey } = await negotiator.authenticate({ 
    unEndPoint, 
    unsignedToken 
  });

**Comment by nicktaras** [comment]
![Screen Shot 2021-10-18 at 12 42 41 pm](https://user-images.githubusercontent.com/6808817/137656788-a56c5b43-552f-4779-927e-eb1543d3a861.png)
![Screen Shot 2021-10-18 at 12 45 23 pm](https://user-images.githubusercontent.com/6808817/137656792-7a046669-14ce-40de-9757-4692730db66e.png)

**Comment by nicktaras** [comment]
@oleggrib can we confirm the inputs/outputs for this function. 

- Unpredictable number
- Proof

**Comment by oleggrib** [comment]
This is how I user it in my DEMO example:
let auth = await n.authenticate({
                unsignedToken: negotiateAnswer.tokens[0],
                unEndPoint: 'https://crypto-verify.herokuapp.com/use-devcon-ticket'
            });

unEndPoint points to the server, what have saved secret and creates Unpredictable number and after that validate signature

this is where it implemented
https://github.com/TokenScript/token-negotiator/blob/refactor-to-ts/src/negotiator/index.ts#L635-L667

after that authenticate() requests outlet and fire method to attest MagicLink and create proof
https://github.com/TokenScript/token-negotiator/blob/refactor-to-ts/src/negotiator/index.ts#L297-L334

**Comment by oleggrib** [comment]
It doesnt save on the server. payload contains expiry data and signed with some secret key, so user cant change content.

**Comment by nicktaras** [comment]
Closing this issue, authentication is now in place inside the code base.
