### ISSUE TITLE
tickStorage is protected

### ISSUE THREAD

**Issue by futantan** [TokenScript/token-negotiator#806]
Migrating from version 2x to 3x, but found this error

<img width="1227" alt="CleanShot 2023-08-22 at 14 59 37@2x" src="https://github.com/TokenScript/token-negotiator/assets/6268441/668f4024-86ec-4045-9969-eaa7b288eb54">

**Comment by nicktaras** [comment]
Thanks @futantan this error wasn’t picked up when implementing into the examples (typescript instance of an Outlet)

Implementation example here:
https://github.com/TokenScript/token-negotiator-examples/blob/main/token-outlet-website/src/index.ts

A work around is to add, 
‘’’’
// @ts-ignore 
tn.storage.migrate….
‘’’’

**Comment by nicktaras** [comment]
This issue has been resolved in the 3.0.2 release. 

Thanks @futantan for raising this issue.
