### ISSUE TITLE
UN signature request missing when UN expire

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#807]
@nicktaras , I discovered a bug, it happen always when UN expire.

Steps to reploduce:
- create onChian issuer ( NFT ) for contract, where you owns some NFTs
- connect Metamask
- request authenticate(), it will create UN and request to sign it
- wait until UN expire
- request authenticate(). TN will display message that authenticate() working, but no request to Metamask. page do nothing until you cancel request and request authenticate again

**Comment by nicktaras** [comment]
Closing this ticket, will be addressed in the next release 3.1.0
