### ISSUE TITLE
Brave & Safari Browser Iframes / Possible UX enhancement

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#86]
The brave browser appears to require a preferences change to enable third party cookies/Iframe to function.

Meaning it's compatible, but likely to be a huge hurdle for users to adopt the Token Negotiator.

This task is to see if there is a workaround to read data from an Iframe via the brave browser.

**Comment by AW-STJ** [comment]
To be done:
- Update documentation
- Update example to include the changes

**Comment by nicktaras** [comment]
Closing issue, a solution is now in place.
