### ISSUE TITLE
Token-Negotiator / authenticator / attestation.id / TokenScript working as one - for demo tokens and product

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#89]
How does Token Negotiator demonstrate mock tokens - using authenticator / attestation.id.

This issue is to consider how we can demonstrate the full attestation / authentication flow of mock tokens.

Ideas:

<img width="1567" alt="Screen Shot 2021-10-28 at 4 19 23 pm" src="https://user-images.githubusercontent.com/6808817/139192338-1565f795-a402-49be-8550-32cb47d8668f.png">

- Could we have tokens with no expiry that can be tested with
- Should we use a complete mock flow, that doesn't need to use attestation.id
- Are there issues in my implementation that are causing this issue?

**Comment by nicktaras** [comment]
Hi @oleggrib,

Do you think there is a process we can implement. So when changes are made to the Authenticator;

- We can generate new mock tokens
- push them to a server / this so the Token Negotiator can consume them

This would also mean the token negotiator examples would need to update e.g. if breaking changes occur. 

Can you have a think about this your side and I'll look too. To see what we can come up with to make this process seamless to manage. 

This so when we make changes that are reflected in our examples and everything is kept in sync.

**Comment by oleggrib** [comment]
Hi, @nicktaras  we need TokenScript file and we can describe token schema in that file, validator type, onchain/offchain and all other properties of that token.
Authenticator, Negotiator, Attestation.id can read that file and read/validate token depends on that config.
@colourful-land , Am I right?

**Comment by nicktaras** [comment]
Closing this ticket, we have since changed the proof that is returned by the TKN into the client (for mock and live tokens).
